version: '3'
services:
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
    volumes:
      - ipfs:/data/ipfs
  backend:
    build: ./backend
    environment:
      - IPFS_API=http://ipfs:5001
    ports:
      - "3000:3000"
    depends_on:
      - ipfs
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  ipfs:
