services:
#  ipfs:
#    image: ipfs/kubo:latest
#    ports:
#      - "5001:5001"
#    volumes:
#      - ipfs:/data/ipfs
#    command: daemon --migrate=true --enable-pubsub-experiment
  peer:
    build: ./orbitdb-peer
    ports:
      - "3000:3000"
  webapp:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - peer
#volumes:
#  ipfs:
